apiVersion: v1
kind: Pod
metadata:
 name: design-pod1
spec:
  containers:
    - name: design-pod1
      image: vish/stress
      resources:
        limits:
          cpu: "1.22"
          memory: "567Mi"
        requests:
          cpu: "0.3"
          memory: "456Mi"
      args:
        - -cpus
        - "1"
        - -mem-total
        - "567Mi"
        - -mem-alloc-size
        - "500Mi"
        - -mem-alloc-sleep
        - "1s"
